import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns


REQUIRED_COLUMNS = [
    "phase",
    "batch_size",
    "duration_s",
    "mean_ttft_s",
    "mean_tpot_s",
]


def load_summary(csv_path: Path) -> pd.DataFrame:
    if not csv_path.exists():
        raise FileNotFoundError(f"Summary CSV not found: {csv_path}")
    df = pd.read_csv(csv_path)
    missing = [c for c in REQUIRED_COLUMNS if c not in df.columns]
    if missing:
        raise ValueError(f"Summary CSV missing columns: {missing}")
    return df


def prepare(df: pd.DataFrame):
    pre = df[df["phase"] == "prefill"].copy().sort_values("batch_size")
    dec = df[df["phase"] == "decode"].copy().sort_values("batch_size")
    if pre.empty or dec.empty:
        raise ValueError("Need both prefill and decode rows in summary CSV")

    pre = pre[["batch_size", "mean_ttft_s"]].rename(columns={"mean_ttft_s": "metric"})
    dec = dec[["batch_size", "mean_tpot_s"]].rename(columns={"mean_tpot_s": "metric"})

    pre["phase"] = "prefill_ttft"
    dec["phase"] = "decode_tpot"
    merged = pd.concat([pre, dec], ignore_index=True)

    normalized = []
    for phase, group in merged.groupby("phase"):
        group = group.sort_values("batch_size").copy()
        base = float(group.iloc[0]["metric"])
        group["norm_metric"] = group["metric"] / base if base > 0 else 0.0
        normalized.append(group)

    norm_df = pd.concat(normalized, ignore_index=True)
    return pre, dec, norm_df


def sensitivity_ratio(norm_df: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for phase, group in norm_df.groupby("phase"):
        g = group.sort_values("batch_size")
        ratio = float(g.iloc[-1]["norm_metric"]) / max(float(g.iloc[0]["norm_metric"]), 1e-12)
        rows.append({"phase": phase, "bs_max_over_bs_min": ratio})
    return pd.DataFrame(rows)


def plot_and_save(pre: pd.DataFrame, dec: pd.DataFrame, norm_df: pd.DataFrame, out_png: Path) -> None:
    sns.set_theme(style="whitegrid", context="talk")

    fig, axes = plt.subplots(1, 2, figsize=(13, 5.2), dpi=150)

    axes[0].plot(pre["batch_size"], pre["metric"], marker="o", linewidth=2.2, label="Prefill TTFT (s)")
    axes[0].plot(dec["batch_size"], dec["metric"], marker="s", linewidth=2.2, label="Decode TPOT (s)")
    axes[0].set_title("Raw Metric vs Batch Size", fontweight="bold")
    axes[0].set_xlabel("Batch Size")
    axes[0].set_ylabel("Time (s)")
    axes[0].legend(frameon=True)

    for phase, group in norm_df.groupby("phase"):
        label = "Prefill TTFT (norm)" if phase == "prefill_ttft" else "Decode TPOT (norm)"
        marker = "o" if phase == "prefill_ttft" else "s"
        axes[1].plot(group["batch_size"], group["norm_metric"], marker=marker, linewidth=2.2, label=label)

    axes[1].set_title("Normalized Sensitivity (Baseline: Min Batch)", fontweight="bold")
    axes[1].set_xlabel("Batch Size")
    axes[1].set_ylabel("Normalized Value")
    axes[1].legend(frameon=True)

    plt.tight_layout()
    out_png.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(out_png, bbox_inches="tight")
    print(f"[plot] Saved: {out_png}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Plot batch-size sensitivity for prefill TTFT vs decode TPOT."
    )
    parser.add_argument(
        "--csv",
        type=str,
        default="./log/prefill_decode_bs_sensitivity_summary.csv",
        help="Summary CSV generated by batch_prefill_decode_sensitivity.py",
    )
    parser.add_argument(
        "--out",
        type=str,
        default="./log/prefill_decode_bs_sensitivity.png",
        help="Output PNG path",
    )
    parser.add_argument(
        "--ratio-out",
        type=str,
        default="./log/prefill_decode_bs_sensitivity_ratio.csv",
        help="Output CSV path for sensitivity ratio summary",
    )
    args = parser.parse_args()

    df = load_summary(Path(args.csv))
    pre, dec, norm_df = prepare(df)
    ratio_df = sensitivity_ratio(norm_df)
    ratio_df.to_csv(args.ratio_out, index=False)
    print("[summary] Sensitivity ratio (bs_max / bs_min):")
    print(ratio_df.to_string(index=False))

    plot_and_save(pre, dec, norm_df, Path(args.out))
    print(f"[summary] Ratio CSV saved: {args.ratio_out}")


if __name__ == "__main__":
    main()
